### ISSUE TITLE
ErrorCode: Calibration File Not Available while using Zedfu App

### ISSUE THREAD

**Issue by sumitjagdale** [stereolabs/zed-examples#1]
Hello,
I have installed new sdk v2, just curious about spatial mapping app within zedfu. I have already calibrated Zed after installation, rather my calibration file exists within following directory  "C:\Users\user\AppData\Roaming\Stereolabs\settings\SN1899".
But when I tried accessing this app for live as well as offline mode I am getting following error message(Attached snapshot).
Please help. Many thanks in advance.!
![zedfu_error](https://cloud.githubusercontent.com/assets/14341835/24837202/ea88f6f2-1d60-11e7-85e2-4ebf1f66f3b5.PNG)

**Comment by sl-braun** [comment]
Hi,

You need to make sure that you have access to the folder Roaming/stereolabs/settings/ without having to type a password. 
Make sure that <user> matches the loggin session (don't log in PUBLIC for example).

In any case, I would recommend to contact the support so that they can make you run a diagnostic.

Best,
/*OB*/

**Comment by sumitjagdale** [comment]
@sl-braun Dear Oliver,
Thank you very much for your feedback. As I could not figure out the issue, simply reinstalled it and it has solved my problem:) 
Best,
Sumit
