### ISSUE TITLE
Disparity accuracy from ZED

### ISSUE THREAD

**Issue by Mostafa-Mansour** [stereolabs/zed-examples#133]
Hi,

I am working on an algorithm that requires the disparity accuracy to be implemented. As far as I know, stereo matching algorithms return the disparity between two points as a gaussian distributed parameter where the mean is the calculated disparity and 'sigma' is the expected error is in the disparity. I want to know if there is any way to get this 'sigma' from the stereo matching algorithm used in zed?

**Comment by WASCHMASCHINE** [comment]
Hi @Mostafa-Mansour,

Here are some thoughts:
1. In the literature some consider the disparity error to be a Laplacian or Cauchy Distribution even. But I assume it is also normally distributed anyway.
2. For an error estimate you would need an accurate and dense reference measurement. Still, only in general for the algorithm, not per pixel.
3. Errors may be strongly correlated between frames.
4. You could use the confidence measurement of the ZED to get a pseudo error since Stereolabs do not disclose the meaning of it. Still, as long as you do not integrate other sensor measurements, I think you can live with a known "relative" error.
