### ISSUE TITLE
the quality of video streaming

### ISSUE THREAD

**Issue by djkayip** [stereolabs/zed-examples#162]
Hi, I'm trying to stream the video.  when some objects move on the screen, I've got a lot artifacts. 

![ZED 7_18_2019 10_57_00 PM](https://user-images.githubusercontent.com/16952020/61464430-32513880-a9b1-11e9-9d8a-24bac142880e.png)

not moving

![ZED 7_18_2019 10_57_16 PM](https://user-images.githubusercontent.com/16952020/61464447-3b420a00-a9b1-11e9-842a-e51f474e2fec.png)

moving hands

I'm planning to stream the video to AWS,which runs YOLO.  Is there any parameters I need to adjust to get better quality?

My setting on the sender side

bitrate = 8000
gop_size =64
adaptive_bitrate = True

I'm using python API AND CUDA 10 on windows

**Comment by obraun-sl** [comment]
This is probably coming from lost packet in the streaming (lost packet means corrupted images until a new IDR frame is reached, depending on the gop size).
Did you try to stream on localhost to check if you have the same behavior ?

**Comment by djkayip** [comment]
streaming on localhost(127.0.0.1) works ok. but if I try to stream between two PCs with a same router, it produces the problem. I tried to increase gop_size up to 256, and change the bitrate (from 1000-10000).  
it doesn't seem to make any difference. 

it there anything I can do?

**Comment by obraun-sl** [comment]
Do you have something else connected on the same router? or only the two PCs?
* Increase gop size and decrease bitrate will reduce the number of lost/corrupted packet.
* Make sure all the ethernet cables are at least cat5E.

**Comment by djkayip** [comment]
Yes, Only two PCs are on the same router. I did try to increase gop size and decrease bitrate. it still produces same problem.  Do you mean I need to change the ethernet cable to the wifi router?

**Comment by khausman502** [comment]
Did you ever come to a resolution for this issue?  I'm facing the exact same problem--streaming works fine on a single machine, but between two machines, I get the macro-blocking during any motion.  Have verified that bandwidth between the machines is sufficient.  I also see that setting the bitrate on the sending side seems to have no effect on the bandwidth I see flowing over the wire.

**Comment by templarares** [comment]
Is there any update/fix regarding this issue yet? I have run into the same issue. Streaming (720Px30FPS) works fine with an ethernet cable, but it became extemely laggy when the cable is replaced with wireless connection, whose bandwidth has been verifited to be sufficient (25Mbps). I, too, observed that varying the birtate seems to have no effect on the ethernet bandwith consumption monitered by Win10's task manager.

**Comment by obraun-sl** [comment]
Hi,
streaming module has been reworked for next major release 3.0.0. This release will be official in the next weeks (end of January). 
That brings more stability and a payload size parameter to optimize the bandwith consumption. 

Wifi is known to brings more collision into stream packet than ethernet cable. Try also to reduce the number of PC connected to the same Wifi Network.

**Comment by templarares** [comment]
Hi Obraun-sl,

Thank you very much for your quick response! And there are some more specific symptoms observed in our tests; as we do not know about the lower-level structure of the "camera streaming" sender sample, do you think they are expected given the current coding in "camera streaming" sender and that the 3.0.0 release would fix them? Thank you very much!

#1. With DEPTH_MODE_NONE, 720P x 30FPS (x 2 Cameras) configured in "camera streaming" sender , the bandwidth consumption is 17Mbps, which is unexpectedly high: normally, with H.265, 720Px30FPS should consume no more than 2 Mbps;

#2.Changing the "bitrate" parameter in "camera streaming" sender  does not seem to take any effect; the bandwidth consumption with the configuration mentioned in #1 stays at 17Mbps regardless to the bitrate value (be it 8000kbps, 4000kbps or 1000kbps).

#3.Our wireless transmitter has working bandwith of 25Mbps (at this bandwith, the ping latency varys from 60ms to 120ms, averaged at about 75ms), which is greater than the 17Mbps mentioned in configuration #1. However, the ZED Unity Plugin cannot display the video stream (screen stays at "Loading camera"). By reducing the FPS from 30 to 15, the "camera straming"'s bandwith consumption is reduced to 9Mbps as expected; at this configuration, the ZED Unity Plugin finally displays the images, but extremely laggy. Do you think this is also caused by the coding in current "camera streaming" sender and will be fixed in the 3.0.0 release? And is there any debug log we can check at the ZED Unity Plugin side to see if we can address the issue from the Receiver's end?

Additionally, we are also considering developing our own solution to make the "TypeC-USB3.0" cable between ZED_M and the PC go wireless. May I know the format of the data stream coming out of the TypeC port/out of the USB3.0 port? And what about the data stream's approximate bitrate, say, with DEPTH_MODE_PERFORMANCE, 720P, 30FPS? 

Thank you very very much!

**Comment by muraiyuya** [comment]
Have you already solved this issue? I'm facing the same problem, between two machines, I get the macro-blocking when the camera moves. I want streaming-video to be much smoother .

**Comment by templarares** [comment]
> Have you already solved this issue? I'm facing the same problem, between two machines, I get the macro-blocking when the camera moves. I want streaming-video to be much smoother .

After updating the ZED SDK to 3.0+, video streaming now works, wirelessly. But my ZED is stationary (objects in the scene do move, though).

**Comment by Zgihu** [comment]
I see.That is good.
In my case, video streaming is so smooth when pc with zed is connected by LAN cable.
However, video streaming stops sometimes when pc with zed is connected by wireless LAN .
How can I solve it? 
If you know it, please teach me!

**Comment by Rutherfordum** [comment]
I'm facing the same problem, between two machines, I get the macro-blocking when the camera moves. I want streaming-video to be much smoother . Help.

**Comment by obraun-sl** [comment]
This can come from two sides : 
- Loss of stream packet. If you are in verbose mode, on the receiver side, you will see some message in console (unexpected size.....) when packets are lost. If this is the case, this most probably comes from the network. Try to use ethernet instead of WiFi, and try to play with the streaming parameters "chunk_size" (increase it most probably to reduce the number of packet for an image). 

- Try to increase the bitrate if there is now corrupted packet but just H26x compression artifacts when moving.
