### ISSUE TITLE
Spatial Mapping

### ISSUE THREAD

**Issue by lcyawym** [stereolabs/zed-examples#202]
Hello，I want to know the Spatial Mapping is using monocular or binocular.And in ZED SDK，there is a tool named ZED FU,it is the same as Spatial Mapping?Thanks

**Comment by obraun-sl** [comment]
Hi,
the spatial mapping is using binocular since it uses the images and the depth to mesh the environment.
ZEDFu and spatial mapping example are very close : they are using the spatial mapping module of the ZED SDK both. 
Take a look here to have a better view of the Spatial mapping module : 
https://www.stereolabs.com/docs/spatial-mapping/

**Comment by lcyawym** [comment]
Thanks for your reply, I understand.
