### ISSUE TITLE
Changing the depth quality of camera.

### ISSUE THREAD

**Issue by ashish2091** [stereolabs/zed-examples#25]
I am running the depth sensing tutorial. What parameters should I use to change depth quality of the camera. Because I am just capturing a flat wall and even at different distances the wall looks too curvy with descent amount of depth error easily visible on the point cloud. I don't know if its the right platform to ask but I would appreciate if anyone can answer this?

**Comment by WASCHMASCHINE** [comment]
Hello @ashish2091, the ZED is a stereo camera and works via finding stereo correspondences between the left and right images. I assume you have a white wall (a homogeneous texture), which will make even flat surfaces noisy because it is hard to match a pure white pixel region with a pure white pixel region.
