### ISSUE TITLE
depth_range_setting in python and resolution help

### ISSUE THREAD

**Issue by Wei10857104** [stereolabs/zed-examples#281]
I use python to code, and try set depth range.
On website https://www.stereolabs.com/docs/depth-sensing/depth-settings/

It said use this code can set depth_max_range.
`zed.set_depth_max_range_value(40)`

But In python i can't find it.

I found `init_params.depth_maximum_distance = 40.0` .

Is this code same effect as zed.set_depth_max_range_value(40).

There is my setting code.

`zed = sl.Camera()

init_params = sl.InitParameters()
init_params.depth_mode = sl.DEPTH_MODE.ULTRA  # Use PERFORMANCE depth mode
init_params.coordinate_units = sl.UNIT.METER  # Use meter units (for depth measurements)
init_params.camera_resolution = sl.RESOLUTION.VGA
init_params.camera_fps = 100
init_params.depth_minimum_distance = 0.015
init_params.depth_maximum_distance = 40.0
sl.MAPPING_RANGE =40

err = zed.open(init_params)
if err != sl.ERROR_CODE.SUCCESS:
    exit(1)

runtime_parameters = sl.RuntimeParameters()
runtime_parameters.sensing_mode = sl.SENSING_MODE.FILL  # Use STANDARD sensing mode

runtime_parameters.confidence_threshold = 150
runtime_parameters.textureness_confidence_threshold = 150`

But i can't  measure to 40m,
It seemed to just 5m.
Because I can't see this people in depth_image.

![73](https://user-images.githubusercontent.com/69885789/91823823-68608300-ec6c-11ea-9083-46865d8d8c83.png)
![73](https://user-images.githubusercontent.com/69885789/91823840-6e566400-ec6c-11ea-94f7-03cb963f7733.png)

**Comment by qt-truong** [comment]
Hi @Wei10857104,

It seems that you displayed the `sl.VIEW.DEPTH` which is not meant to be used to estimate depth measurements. 
In order to check that your depth_minimum_distance and depth_maximum_distance are well set, you should instead retrieve your depth map with `zed.retrieve_measure(mat, sl.MEASURE.DEPTH)` and check that the values in your depth map are consistent with your min/max depths.

Also, note that you cannot set you depth_minimum_distance to a value below 0.2m for ZED2 (resp. 0.3 for ZED and 0.1m for ZED mini -> See documentation here :  [API ref](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1InitParameters.html#a7c98056cb987d0a2ae936104364ddaa3) )
