### ISSUE TITLE
some problems about object detection

### ISSUE THREAD

**Issue by Zhang-Qinghui** [stereolabs/zed-examples#283]
Hello，why do I keep getting stuck at the step of downloading the model when using the 3d detection example.As shown in the picture
![image](https://user-images.githubusercontent.com/49428118/92678106-ce799400-f357-11ea-80ff-19e8f5429b27.png)

**Comment by obraun-sl** [comment]
Hi,
The model to be download is around 200Mb heavy. Make sure you are waiting enough according to your internet speed.
Once downloaded, the module will start to optimize the model for you graphic card.

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply. You are right. But when I downloaded the model and ran it again, there was another error“段错误（核心已转储）”. Why does this happen？
![image](https://user-images.githubusercontent.com/49428118/92737026-5fc72580-f3ad-11ea-8a8d-8bbb681779f2.png)

**Comment by obraun-sl** [comment]
Can you give more precision about the graphic card used ?

**Comment by Zhang-Qinghui** [comment]
Of course.The graphic card I used is GTX 750Ti. Is it because of the graphics card?

**Comment by obraun-sl** [comment]
It might come from that. The GTX750 does not have a lot of GPU memory and AI model does require a lot. 
You can try to reduce the GPU memory used by the depth map by setting the depth mode to PERFORMANCE instead of ULTRA first. 
Then the HUMAN_BODY_FAST model has less requirement on GPU memory and might be a better fit for your graphic card.

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply. Now I try to use tx2 to run 3d detection example. Could you please tell me where the model will be downloaded?
