### ISSUE TITLE
focal length and field of view

### ISSUE THREAD

**Issue by nikky4D** [stereolabs/zed-examples#32]
Hi,

thanks for the help with finding the focal length. 

I am trying to relate the field of view to the focal length. My understanding is that the relation 
fov = 2 * atan ( (image sensor width/2) / focal length ). From this, would my image sensor width be my resolution (eg 720 for  a 1280x720 image) or actual values of the sensor size? 

For the sensor size, is it correct to say that for 1280x720 resolution, with pixel_size_mm as 0.004mm, the sensor area is (0.004*0.004) * 4000000 .  It says on the zed spec that we have 4M pixels. Hence the sensor size is sqrt ( (0.004*0.004) * 4000000)? 

Any help is greatly appreciated.

**Comment by WASCHMASCHINE** [comment]
Formula looks fine. 
I think you can compute the horizontal and vertical fov on their own. 
You can either choose pixels or meter since they sensor width and focal length will have the same unit for the angle. 
Let's say fx=700px and width=1280px. 
2 * atan ( (1280/2) / 700) = 84.87°

Does that make sense? Less than 45° per side, seems plausible.

**Comment by nikky4D** [comment]
Thanks.
