### ISSUE TITLE
Is this coordinate in the camera system or in the world system?

### ISSUE THREAD

**Issue by Kismetzc** [stereolabs/zed-examples#410]
in this sample [body_tracking](https://github.com/stereolabs/zed-examples/blob/650cef365e9dbfd71760d9874cb80e3a27ad9f30/tutorials/tutorial%208%20-%20body%20tracking/python/body_tracking.py#L98)

**Comment by obraun-sl** [comment]
Keypoints are expressed in the measure reference frame as mentioned here : 
https://www.stereolabs.com/docs/api/classsl_1_1ObjectData.html#abbcf08d0ee3800edda16f668dd9c4696

Therefore in this example, Since the runtime parameters are left to default values (not provided in the grab() function), the keypoints are provided in the camera system.

**Comment by Kismetzc** [comment]
Okay, I got it. Thank you
