### ISSUE TITLE
Depth Sensing only for red object

### ISSUE THREAD

**Issue by guptara** [stereolabs/zed-examples#43]
I am using ZED camera and OpenCV 3.1.0 ( C++ ) with Visual Studio 2015 to measure the depth.
I want to measure the depth by detecting the red object but I am facing difficulty in detecting the red object and measuring depth. Can you help me with this ?

**Comment by obraun-sl** [comment]
Hi,

Regarding the color detection, this will be related to OpenCV only. There is different ways of doing that and you will find some examples online. One solution may be to do a HSV segmentation, and create a binary image (white/1 in HSV limits, black/0 otherwise). 

Then use retrieveMeasure() to get the depth map from the ZED SDK and extract the value(s) at each "white" pixel.

Best,
/*OB*/
