### ISSUE TITLE
CUDA 11.5 not ready even after reboot

### ISSUE THREAD

**Issue by Pixionrevolution** [stereolabs/zed-examples#450]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When I launch ZED Diagnostic , ZED SDK 3.6.2 is telling me "CUDA 11.5 not ready - Your computer needs to be restarted" constantly.
What I did: 
- Rebooted several times, obviously.
- Uninstalled everything (ZED SDK 3.6.2 , CUDA 11.5.1)
- Reinstalled everything

CUDA is well detected, and working with the CUDA Samples but somehow is still "not ready" enough for ZED SDK. 
I tried everything I could before reaching out to you but I don't know what else I can do.
I tried with different versions of SDK and CUDA reaching everytime the same outcome.

### Steps to Reproduce

1.Install ZED SDK 
2.Install CUDA
3.Launch ZED Diagnostic
...

### Expected Result

All green checkboxes

### Actual Result

All green checkboxes except ZED SDK

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows 10
CPU: i7- 7700HQ 2.8ghz
GPU: GTX 1080 Max-Q
RAM: 24go
```

**Comment by adujardin** [comment]
Thanks for the report, this is a known issue for CUDA 11.X versions. ZED Diagnostic tool doesn't support well the new compatibility for all minor versions introduced with CUDA 11. The fix for this didn't make it for the 3.6.2 patch. It should be ready for the next versions.

Sorry for the inconvenience and don't worry about the report, you can probably ignore it if the tools and samples are working correctly.
